### ISSUE TITLE
error checkerserial

### ISSUE THREAD

**Issue by christiansantos1** [hansalemaos/jerryrigserialver#1]
![Sem título](https://github.com/hansalemaos/jerryrigserialver/assets/124522878/2d4377ee-f17f-47ed-ad5b-c56151e0c06e)

quando insiro o serial number no código que verifica a Keys, imprime esse erro.

**Comment by hansalemaos** [comment]
Tente primeiro isso: pip install pycryptodomex==3.18.0
E veja se ainda está aparecendo. 
Coloque todo seu código (sem seu app)

**Comment by christiansantos1** [comment]
> Tente primeiro isso: pip install pycryptodomex==3.18.0 E veja se ainda está aparecendo. Coloque todo seu código (sem seu app)

![Sem título](https://github.com/hansalemaos/jerryrigserialver/assets/124522878/6c8e2f14-d87c-46e2-9fc7-0e0a2e44b30e)

Estou sofrendo esse novo erro, mesmo com todas bibliotecas requeridas instaladas.

**Comment by hansalemaos** [comment]
Tire o .split()

**Comment by christiansantos1** [comment]
> Tire o .split()

![Sem título](https://github.com/hansalemaos/jerryrigserialver/assets/124522878/e05447cd-f705-425f-956a-c79a22086e13)

**Comment by hansalemaos** [comment]
Qual serialnumber foi gerado?
Uma tipo assim:  566978376a4b356956775955427a4779636e533856705a59534d314369387735526e59744230396f6c6771795256675a31365a756947344753616d3757536d5961704f736a362f63506871724a792f3845664d4845773d3d475ac18a6927938b4ede1613058f253e

**Comment by hansalemaos** [comment]
Aqui deu o mesmo erro, tentei encontrar, mas não consegui. Pode ser tanta coisa :( Vou tentar fazer nesta semana.

**Comment by hansalemaos** [comment]
Primeiro, vou tentar instalar versões antigas das dependências. se não der, vou ver se é por causa de transfer.sh

**Comment by christiansantos1** [comment]
uma pena, esse codigo é muito interessante, estou no aguardo da atualização, abraço!!

**Comment by christiansantos1** [comment]
você sabe alguma biblioteca parecida, com proteção uuid ou tempo de expiração com uma key gerada a partir de mim? obrigado.

**Comment by hansalemaos** [comment]
Acabei de analisar. Parece que o formato de transfer.sh mudou. Vou tentar arrumar nessa semana. Não tem nada parecido, só comercial, por isso, fiz.

**Comment by hansalemaos** [comment]
Acho que é isso (de transfer.sh): This release include the fix for the bug as well as the new feature that introduced the bug: ie, using and htpasswd file for basic auth credentials.

**Comment by hansalemaos** [comment]
Cara, acho que consegui consertar. Desinstale os pacotes e instale novamente. 

   hardcodedpasswort_url="5248614597016233"

é irrelevante por enquanto

Por favor, avise-me se deu certo.

**Comment by christiansantos1** [comment]
> Cara, acho que consegui consertar. Desinstale os pacotes e instale novamente.
> 
> hardcodedpasswort_url="5248614597016233"
> 
> é irrelevante por enquanto
> 
> Por favor, avise-me se deu certo.
![Sem título](https://github.com/hansalemaos/jerryrigserialver/assets/124522878/91ea8d39-7af1-445f-aea4-a143e9203cfc)


Erro solucionado!! Obrigado amigo.

**Comment by hansalemaos** [comment]
Eu que agradeço porque você encontrou o bug :)

**Comment by christiansantos1** [comment]
> Eu que agradeço porque você encontrou o bug :)

Uma duvida, ao gerar a key e o cliente executar em 1 pc e depois usar a key em outro pc, a key funcionara?

pois eu criei uma key usei em outro pc via anydesk, e também usei a mesma key no meu pc e a key funcionou o meu código.

**Comment by hansalemaos** [comment]
nao, so uma vez, mas pode gerar outro serialnumber. no entanto, as mudanças que tive fazer hoje talvez tenham mudado algumas coisas. Por favor, teste e informe-me, ok?

**Comment by christiansantos1** [comment]
> nao, so uma vez, mas pode gerar outro serialnumber. no entanto, as mudanças que tive fazer hoje talvez tenham mudado algumas coisas. Por favor, teste e informe-me, ok?

pelo que testei, o código pode ser usado em outros produtos com a sua biblioteca, e pode ser usado em outros computadores, mas mesmo assim é um ótimo código de expiração com key, caso concerte o bug do serial number validando em outros codigos e computadores, ficará perfeito, obrigado amigo.

**Comment by hansalemaos** [comment]
hmm... que estranho. Esta linha deveria cuidar desse problema:         

`newlink = upload_file_to_transfer(self.filepath, password=self.password, maxdownloads=1)  
`
Porque o serialnumber que foi subido, só pode ser acessado uma única vez (para evitar a instalação em outros PCs
Pode ser que o maxdownloads não esteja funcionando como deveria no transfer.sh. Vou testar logo - provavelmente hoje ainda. 

Você testou com 2 computadores diferentes (que nenhum seja aquele que gerou o serialnumber)? Para resolver a parte de poder ser usado em outros produtos, implementei isso: 

```
addinformationtoserial=(
        "info1", 'prata', 'ouro','diamante',
        "info2",'blablabla'
    ),

```
Minha ideia inicial foi oferecer um produto (app) com 3 categorias, por exemplo: Membership Silver, Gold, Diamond 
Depois você pode checar no código qual Membership a pessoa tem. Essa parte também resolve a instalação para outro app/produto, embora eu nem esteja pensado nisso.  addinformationtoserial te ajuda para customizar as restrições, você tem a opção de obter/mandar informações adicionais que seu cliente não vai saber porque estão escondidas dentro do serialnumber.

**Comment by christiansantos1** [comment]
> hmm... que estranho. Esta linha deveria cuidar desse problema:
> 
> `newlink = upload_file_to_transfer(self.filepath, password=self.password, maxdownloads=1) ` Porque o serialnumber que foi subido, só pode ser acessado uma única vez (para evitar a instalação em outros PCs Pode ser que o maxdownloads não esteja funcionando como deveria no transfer.sh. Vou testar logo - provavelmente hoje ainda.
> 
> Você testou com 2 computadores diferentes (que nenhum seja aquele que gerou o serialnumber)? Para resolver a parte de poder ser usado em outros produtos, implementei isso:
> 
> ```
> addinformationtoserial=(
>         "info1", 'prata', 'ouro','diamante',
>         "info2",'blablabla'
>     ),
> ```
> 
> Minha ideia inicial foi oferecer um produto (app) com 3 categorias, por exemplo: Membership Silver, Gold, Diamond Depois você pode checar no código qual Membership a pessoa tem. Essa parte também resolve a instalação para outro app/produto, embora eu nem esteja pensado nisso. addinformationtoserial te ajuda para customizar as restrições, você tem a opção de obter/mandar informações adicionais que seu cliente não vai saber porque estão escondidas dentro do serialnumber.

Achei bacana a ideia dos planos, como disse testei o serial number após a resolução do bug da api, e o serialnumber era aceito em ambos computadores e ambos codigos, como se nao houvesse restrição. Espero que teste e veja se fiz algo errado, pra não te atrapalhar em um erro meu rsrs.
E só mais uma observação “ serialusedanotherpc” não consta print para o cliente, caso a instalação seja feita no outro pc, so imprime se a licença é valida, ou expirada.

**Comment by hansalemaos** [comment]
hmmm... interessante. Faça um favor para mim: Teste em 2 computadores com o mesmo app e em 2 computadores com 2 apps diferentes.

**Comment by christiansantos1** [comment]
> hmmm... interessante. Faça um favor para mim: Teste em 2 computadores com o mesmo app e em 2 computadores com 2 apps diferentes.

testei em 2 computadores o mesmo codigo e a key foi aceita normalmente, no codigo sem meu app, e com o codigo com meu app ambos aceitou a key que ja foi usada em outro computador, pode ser um bug do transfer.sh que ta aceitando mais de 1 download.

**Comment by hansalemaos** [comment]
Pode ser! Vou observar isso e testar quando tiver um pouco mais tempo! Se quiser melhorar o código, fique vontade! Ficaria feliz com gente me ajudando.

**Comment by DouglasAlexDEV** [comment]
![image](https://github.com/user-attachments/assets/25591539-fb6c-4327-847e-bde75b83a386)
o meu da esse erro, confesso que é minha primeira vez haha, eu já instalei com pip install

**Comment by hansalemaos** [comment]
São 2:
https://github.com/hansalemaos/jerryrigserialgen
https://github.com/hansalemaos/jerryrigserialver
Mas use a versão daqui do github
